import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { FigmaClient } from './client';
import { extractVariableTokens, fetchVariables } from './variables';

function parseFileKey(input: string): string {
  const match = input.match(/figma\.com\/(?:design|file|board|make)\/([A-Za-z0-9]+)/);
  return match ? match[1] : input.trim();
}

function toTsFile(tokens: { modes: string[]; tokensByMode: Record<string, Record<string, string>> }): string {
  const lines: string[] = [
    '// generated by @dp/figma-extractor — do not edit by hand',
    'export const rawTokens = {',
  ];
  for (const mode of tokens.modes) {
    lines.push(`  ${JSON.stringify(mode)}: {`);
    for (const [k, v] of Object.entries(tokens.tokensByMode[mode])) {
      lines.push(`    ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
    }
    lines.push('  },');
  }
  lines.push('} as const;', '', 'export type ThemeName = keyof typeof rawTokens;', '');
  return lines.join('\n');
}

async function main() {
  const token = process.env.FIGMA_TOKEN;
  const rawKey = process.env.FIGMA_FILE_KEY ?? process.argv[2];
  if (!token || !rawKey) {
    console.error('usage: FIGMA_TOKEN=xxx FIGMA_FILE_KEY=yyy dp-extract-tokens');
    process.exit(1);
  }
  const fileKey = parseFileKey(rawKey);
  const client = new FigmaClient({ token });

  console.log(`fetching variables for ${fileKey}…`);
  try {
    const resp = await fetchVariables(client, fileKey);
    const tokens = extractVariableTokens(resp);
    const outDir = resolve(process.cwd(), '.extracted');
    mkdirSync(outDir, { recursive: true });

    writeFileSync(resolve(outDir, 'tokens.json'), JSON.stringify(tokens, null, 2));
    const tsPath = resolve(process.cwd(), 'packages/tokens/src/tokens.generated.ts');
    writeFileSync(tsPath, toTsFile(tokens), 'utf8');

    const totalTokens = Object.values(tokens.tokensByMode).reduce((n, t) => n + Object.keys(t).length, 0);
    console.log(`wrote ${totalTokens} tokens across ${tokens.modes.length} modes → ${tsPath}`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.includes('403') || msg.includes('404')) {
      console.error(
        'Figma Variables API unavailable (requires Enterprise plan). Skipping tokens sync.',
      );
      console.error(msg);
      process.exit(0);
    }
    throw err;
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
