import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { FigmaClient } from './client';
import {
  extractVariableTokens,
  fetchVariables,
  type ExtractedVariableTokens,
} from './variables';

function parseFileKey(input: string): string {
  const match = input.match(/figma\.com\/(?:design|file|board|make)\/([A-Za-z0-9]+)/);
  return match ? match[1] : input.trim();
}

function emitTsFile(tokens: ExtractedVariableTokens): string {
  const byMode: Record<string, Record<string, string>> = {};
  for (const mode of tokens.modes) {
    byMode[mode] = {};
    for (const [cssVar, entry] of Object.entries(tokens.tokensByMode[mode])) {
      byMode[mode][cssVar] = entry.value;
    }
  }

  const groupsByMode: Record<string, Record<string, Record<string, string>>> = {};
  for (const mode of tokens.modes) {
    groupsByMode[mode] = {};
    for (const entry of Object.values(tokens.tokensByMode[mode])) {
      const leaf = entry.name.replace(new RegExp(`^${entry.group}-`), '') || entry.name;
      groupsByMode[mode][entry.group] ??= {};
      groupsByMode[mode][entry.group][leaf] = entry.value;
    }
  }

  const lines: string[] = [
    '// generated by @dp/figma-extractor — do not edit by hand',
    `export const defaultMode = ${JSON.stringify(tokens.defaultMode)} as const;`,
    `export const modes = ${JSON.stringify(tokens.modes)} as const;`,
    `export const collections = ${JSON.stringify(tokens.collections)} as const;`,
    '',
    'export const rawTokens = ',
    `${JSON.stringify(byMode, null, 2)} as const;`,
    '',
    'export const tokenGroups = ',
    `${JSON.stringify(groupsByMode, null, 2)} as const;`,
    '',
    'export type ThemeName = keyof typeof rawTokens;',
    '',
  ];
  return lines.join('\n');
}

function emitCssFile(tokens: ExtractedVariableTokens): string {
  const lines: string[] = ['/* generated by @dp/figma-extractor — do not edit */'];
  for (const mode of tokens.modes) {
    const selector = mode === tokens.defaultMode ? `:root, [data-theme="${mode}"]` : `[data-theme="${mode}"]`;
    lines.push(`${selector} {`);
    for (const [cssVar, entry] of Object.entries(tokens.tokensByMode[mode])) {
      lines.push(`  ${cssVar}: ${entry.value};`);
    }
    lines.push('}', '');
  }
  return lines.join('\n');
}

function summarize(tokens: ExtractedVariableTokens): string {
  const counts: Record<string, number> = {};
  for (const mode of tokens.modes) {
    for (const entry of Object.values(tokens.tokensByMode[mode])) {
      counts[`${mode}/${entry.collection}/${entry.type}`] =
        (counts[`${mode}/${entry.collection}/${entry.type}`] ?? 0) + 1;
    }
  }
  return Object.entries(counts)
    .map(([k, n]) => `  ${k}: ${n}`)
    .join('\n');
}

async function main() {
  const token = process.env.FIGMA_TOKEN;
  const rawKey = process.env.FIGMA_FILE_KEY ?? process.argv[2];
  if (!token || !rawKey) {
    console.error('usage: FIGMA_TOKEN=xxx FIGMA_FILE_KEY=yyy pnpm ds:tokens');
    process.exit(1);
  }
  const fileKey = parseFileKey(rawKey);
  const client = new FigmaClient({ token });

  console.log(`fetching variables for ${fileKey}…`);

  let resp;
  try {
    resp = await fetchVariables(client, fileKey);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (msg.includes('403')) {
      console.error(
        '\nFigma Variables API returned 403. Two likely causes:',
        '\n  1. Your PAT lacks the `file_variables:read` scope. Regenerate at https://www.figma.com/settings and tick the scope box.',
        '\n  2. The Variables REST API requires a Figma file on an Enterprise plan.',
        '\n\nRaw error:',
        msg,
      );
      process.exit(1);
    }
    if (msg.includes('404')) {
      console.error('File not found or no local variables. Raw error:', msg);
      process.exit(1);
    }
    throw err;
  }

  const tokens = extractVariableTokens(resp);

  const outDir = resolve(process.cwd(), '.extracted');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(resolve(outDir, 'tokens.json'), JSON.stringify(tokens, null, 2));

  const tsPath = resolve(process.cwd(), 'packages/tokens/src/tokens.generated.ts');
  writeFileSync(tsPath, emitTsFile(tokens), 'utf8');

  const cssPath = resolve(process.cwd(), 'packages/tokens/src/tokens.generated.css');
  writeFileSync(cssPath, emitCssFile(tokens), 'utf8');

  const totalTokens = tokens.modes.reduce(
    (n, m) => n + Object.keys(tokens.tokensByMode[m]).length,
    0,
  );
  console.log(`\nwrote ${totalTokens} tokens across ${tokens.modes.length} modes.`);
  console.log(`default mode: ${tokens.defaultMode}`);
  console.log(`collections: ${tokens.collections.join(', ')}`);
  console.log(`\n${summarize(tokens)}`);
  console.log(`\n→ ${tsPath}\n→ ${cssPath}\n→ ${resolve(outDir, 'tokens.json')}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
